<?php

return [
    'front' => [
        [
            'name'                => 'Dashboard',
            'description'         => null,
            'url'                 => '/admin/dashboard',
            'type'                => 'Page',
            'order'               => 0,
            'icon'                => 'fa-home',
            'is_active'           => 1,
            'is_shown_on_menu'    => 1,
            'is_publicly_visible' => 0,
        ],
        [
            'name'                => 'Configuration',
            'description'         => null,
            'url'                 => '#',
            'type'                => 'Module',
            'order'               => 0,
            'icon'                => 'fa-cog',
            'is_active'           => 1,
            'is_shown_on_menu'    => 1,
            'is_publicly_visible' => 0,
            'children'            => [
                [
                    'name'                => 'Module Manager',
                    'description'         => null,
                    'url'                 => '/admin/modules',
                    'type'                => 'Module',
                    'order'               => 1,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'                => 'List all modules',
                            'description'         => null,
                            'url'                 => '/admin/modules',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-list',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'module search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'module listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add modules',
                            'description'         => null,
                            'url'                 => '/admin/modules/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add module',
                                    'slug'           => 'add-module',
                                    'description'    => 'add module details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'name'                => 'Page Manager',
                    'description'         => null,
                    'url'                 => '/admin/pages',
                    'type'                => 'Module',
                    'order'               => 1,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'                => 'List all pages',
                            'description'         => null,
                            'url'                 => '/admin/pages',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-list',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'page search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'page listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add pages',
                            'description'         => null,
                            'url'                 => '/admin/pages/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add page',
                                    'slug'           => 'add-page',
                                    'description'    => 'add page details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'name'                => 'Widgets Manager',
                    'description'         => null,
                    'url'                 => '/admin/widgets',
                    'type'                => 'Module',
                    'order'               => 2,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'                => 'List all widgets',
                            'description'         => null,
                            'url'                 => '/admin/widgets',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-list',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'widget search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                    'is_publicly_visible' => 0,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'widget listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                    'is_publicly_visible' => 0,                                    
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add widgets',
                            'description'         => null,
                            'url'                 => '/admin/widgets/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add widget',
                                    'slug'           => 'add-widget',
                                    'description'    => 'add widget details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                    'is_publicly_visible' => 0,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'name'                => 'User',
                    'description'         => null,
                    'url'                 => '/admin/users',
                    'type'                => 'Module',
                    'order'               => 3,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'                => 'List all user',
                            'description'         => null,
                            'url'                 => '/admin/users',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-list',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'user search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'user listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add user',
                            'description'         => null,
                            'url'                 => '/admin/users/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add user',
                                    'slug'           => 'add-user',
                                    'description'    => 'add user details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'name'                => 'Group',
                    'description'         => null,
                    'url'                 => '/admin/groups',
                    'type'                => 'Module',
                    'order'               => 4,
                    'icon'                => 'fa-sign-in',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'                => 'List all group',
                            'description'         => null,
                            'url'                 => '/admin/groups',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-list',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'group search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'group listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add group',
                            'description'         => null,
                            'url'                 => '/admin/groups/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add group',
                                    'slug'           => 'add-group',
                                    'description'    => 'add group details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],

    'admin' => [
        [
            'name'                => 'Home',
            'description'         => null,
            'url'                 => '/admin/home',
            'type'                => 'Page',
            'order'               => 0,
            'icon'                => 'fa-home',
            'is_active'           => 1,
            'is_shown_on_menu'    => 1,
            'is_publicly_visible' => 0,
        ],

        [
            'name'                  => 'Organisation',
            'description'           => null,
            'url'                   => '#',
            'type'                  => 'Module',
            'order'                 => 0,
            'icon'                  => 'fa-coffee',
            'is_active'             => 1,
            'is_shown_on_menu'      => 1,
            'is_publicly_visible'   => 0,
            'children'              => [
                [
                    'name'             => 'User Manager',
                    'description'      => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage users',
                            'description'      => null,
                            'url'              => '/admin/users',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new user',
                            'description'      => null,
                            'url'              => '/admin/users/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ]
                ],
                [
                    'name'             => 'Role manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage role',
                            'description'           => null,
                            'url'              => '/admin/groups',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new role',
                            'description'           => null,
                            'url'              => '/admin/groups/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
                [
                    'name'             => 'Client manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage client',
                            'description'           => null,
                            'url'              => '/admin/clients',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new client',
                            'description'           => null,
                            'url'              => '/admin/clients/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
                [
                    'name'             => 'Assets manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage assets',
                            'description'           => null,
                            'url'              => '/admin/assets',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new asset',
                            'description'           => null,
                            'url'              => '/admin/assets/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
                [
                    'name'             => 'Department manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Manage department',
                            'description'           => null,
                            'url'              => '/admin/departments',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ]
                ],
                [
                    'name'             => 'Technology manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Manage technology',
                            'description'           => null,
                            'url'              => '/admin/technologies',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
            ],
        ],

        [
            'name'             => 'Projects',
            'description'           => null,
            'url'              => '#',
            'type'             => 'Module',
            'order'            => 0,
            'icon'             => 'fa-code',
            'is_active'        => 1,
            'is_shown_on_menu' => 1,
            'is_publicly_visible'   => 0,
            'children'              => [
                [
                    'name'             => 'Project Manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage projects',
                            'description'           => null,
                            'url'              => '/admin/projects',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new project',
                            'description'           => null,
                            'url'              => '/admin/projects/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
            ]
        ],

        [
            'name'             => 'Human resource',
            'description'           => null,
            'url'              => '#',
            'type'             => 'Module',
            'order'            => 0,
            'icon'             => 'fa-users',
            'is_active'        => 1,
            'is_shown_on_menu' => 1,
            'is_publicly_visible'   => 0,
            'children'              => [
                [
                    'name'             => 'Recruitment manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Manage recruitment',
                            'description'           => null,
                            'url'              => '/admin/recruitments',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new recruitment',
                            'description'           => null,
                            'url'              => '/admin/recruitments/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ],
                ],
                [
                    'name'             => 'Vacancy manager',
                    'description'           => null,
                    'url'              => '#',
                    'type'             => 'Module',
                    'order'            => 0,
                    'icon'             => 'fa-user',
                    'is_active'        => 1,
                    'is_shown_on_menu' => 1,
                    'is_publicly_visible'   => 0,
                    'children'              => [
                        [
                            'name'             => 'Manage vacancy',
                            'description'           => null,
                            'url'              => '/admin/vacancies',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-sliders',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'             => 'Add new vacancy',
                            'description'           => null,
                            'url'              => '/admin/vacancies/create',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-plus-square',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                    ]
                ],
            ],
        ],



        [
            'name'                => 'Configuration',
            'description'         => null,
            'url'                 => '#',
            'type'                => 'Module',
            'order'               => 0,
            'icon'                => 'fa-gears',
            'is_active'           => 1,
            'is_shown_on_menu'    => 1,
            'is_publicly_visible' => 0,
            'children'            => [
                [
                    'name'                => 'Module manager',
                    'description'         => null,
                    'url'                 => '/admin/modules',
                    'type'                => 'Module',
                    'order'               => 0,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'                => 'Manage module',
                            'description'         => null,
                            'url'                 => '/admin/modules',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-sliders',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'module search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'module listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add new module',
                            'description'         => null,
                            'url'                 => '/admin/modules/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus-square',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add module',
                                    'slug'           => 'add-module',
                                    'description'    => 'add module details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'name'                => 'Widget manager',
                    'description'         => null,
                    'url'                 => '#',
                    'type'                => 'Module',
                    'order'               => 0,
                    'icon'                => 'fa-user',
                    'is_active'           => 1,
                    'is_shown_on_menu'    => 1,
                    'is_publicly_visible' => 0,
                    'children'            => [
                        [
                            'name'             => 'Dashboard',
                            'description'      => null,
                            'url'              => '#',
                            'type'             => 'Page',
                            'order'            => 0,
                            'icon'             => 'fa-dashboard',
                            'is_active'        => 1,
                            'is_shown_on_menu' => 1,
                            'is_publicly_visible'   => 0,
                        ],
                        [
                            'name'                => 'Manage widget',
                            'description'         => null,
                            'url'                 => '/admin/widgets',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-sliders',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Filter',
                                    'slug'           => 'filter',
                                    'description'    => 'widget search filter',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                                [
                                    'icon'           => 'fa fa-gear fa-lg',
                                    'name'           => 'Listing',
                                    'slug'           => 'listing',
                                    'description'    => 'widget listing',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                        [
                            'name'                => 'Add new widget',
                            'description'         => null,
                            'url'                 => '/admin/widgets/create',
                            'type'                => 'Page',
                            'order'               => 0,
                            'icon'                => 'fa-plus-square',
                            'is_active'           => 1,
                            'is_shown_on_menu'    => 1,
                            'is_publicly_visible' => 0,
                            'widget'              => [
                                [
                                    'icon'           => 'fa fa-user fa-lg',
                                    'name'           => 'Add widget',
                                    'slug'           => 'add-widget',
                                    'description'    => 'add widget details',
                                    'width'          => '100%',
                                    'status'         => 1,
                                    'settings'       => null,
                                    'widget_type_id' => 1,
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
